es_name: "ARS_native"
problem_type: "brax"
env_name: "ant"
normalize: true
es_config:
  pop_size: 1024
  elite_ratio: 0.05
  init_stdev: 0.05
  decay_stdev: 0.999
  limit_stdev: 0.001
num_tests: 128
n_repeats: 16
max_iter: 300
test_interval: 100
log_interval: 20
seed: 42
gpu_id: 0
debug: false