es_name: "ARS_native"
problem_type: "cartpole_easy"
normalize: false
es_config:
  pop_size: 100
  elite_ratio: 0.1
  init_stdev: 0.05
  decay_stdev: 0.999
  limit_stdev: 0.01
num_tests: 100
n_repeats: 16
max_iter: 2000
test_interval: 100
log_interval: 50
seed: 42
gpu_id: 0
debug: false