es_name: "ARS_native"
problem_type: "cartpole_easy"
normalize: false
es_config:
  pop_size: 100
  top_k: 10 
  noise_stddev: 0.03
hidden_size: 64
num_tests: 100
n_repeats: 16
max_iter: 1000
test_interval: 100
log_interval: 50
seed: 42
gpu_id: 0
debug: false